# Created by trellis-cli v0.9.2
# Documentation: https://roots.io/trellis/docs/wordpress-sites/

wordpress_sites:
  stage-tomasgarciapiriz.com:
    site_hosts:
    - canonical: tomasgarciapiriz.e451.net
    local_path: ../site
    branch: master
    repo: git@github.com:aitormendez/tomasgarciapiriz.git
    repo_subtree_path: site
    multisite:
      enabled: false
    ssl:
      enabled: true
      provider: letsencrypt
    cache:
      enabled: false
